# Generated by Django 3.2.25 on 2024-03-13 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField(default=None)),
                ('years_of_experience', models.CharField(max_length=10)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_plate', models.CharField(max_length=30)),
                ('end_destination', models.CharField(max_length=30)),
                ('time_of_departure', models.TimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('max_seats', models.IntegerField()),
                ('seats_available', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'On platform'), (1, 'Arriving'), (2, 'Leaving'), (3, 'Left')])),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.driver')),
            ],
        ),
    ]
