# Generated by Django 3.2.25 on 2024-03-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='years_of_experience',
            field=models.IntegerField(),
        ),
    ]
